language: node_js
node_js:
- '0.10'
after_success:
- npm run jsdoc
- cat artifacts/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: k4kpAZcA1Mu7LHs58m4JkMbGtpWPI8BPYqmqKVfHBE21daaqRYgpHOiLyWiFhv83xkiOWWfDAS2svvS2h2jDmaRzieVBlonQlhGgDEu123Mobvi8nUxeu6bNxoFSRwKXVx8uTCGKmzwqWz870Y6d7+TUQnMhhdl0GRB2tqAhY0A=
deploy:
- provider: s3
  access_key_id: AKIAJ26WU3ZV2SHW7KDA
  secret_access_key:
    secure: E8Kac865/1GOF8rCngEnSOlalIENoa6PmJCeerdmu8CiPxuZmkOckJOTX4RkDvlp+ZYWSvmY+HRo5niqXdaYjyERqrrJ6HZaP96cPGPO9D4EV5+MpbzGv6xt/40JeXl/mrSBLB8PdKHNcMvCcPY/Jzcop2v8lNgjYYq4yxPdXgY=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: exec-sh/master
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: master
- provider: s3
  access_key_id: AKIAJ26WU3ZV2SHW7KDA
  secret_access_key:
    secure: E8Kac865/1GOF8rCngEnSOlalIENoa6PmJCeerdmu8CiPxuZmkOckJOTX4RkDvlp+ZYWSvmY+HRo5niqXdaYjyERqrrJ6HZaP96cPGPO9D4EV5+MpbzGv6xt/40JeXl/mrSBLB8PdKHNcMvCcPY/Jzcop2v8lNgjYYq4yxPdXgY=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: exec-sh/develop
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: develop
